Catch NoClassDefFoundErrors. These indicate that while a superclass is available on the classpath, a class it depends on is not. As this code is currently catching ClassNotFound exceptions anyway, this is not a major change. It will log a warning.
git-svn-id: https://svn.apache.org/repos/asf/ant/core/trunk@268484 13f79535-47bb-0310-9956-ffa450edef68